import Klondike.Relabel

/-!
# The pile transposition — the position-level symmetry Π

The twin/suit fibration (`Klondike/Relabel.lean`) renamed *cards*;
this file is its position analogue: the group generated by permuting
whole tableau piles — the visible runs, the hidden stacks (the deal
slices truncated by the depths, which travel with the slices), and
every anchor *seat* (`Sum.inl a` bases re-anchor; a card seated on
another card rides along — the transposition never touches
card-seats).  The stock cycle, the foundation heights and the draw
step stay fixed: permuting piles commutes with the draw machinery by
construction.

The family (sorry-free, axiom-clean):

* §1–§3 the action: `Anchor.swap i j`, `Base.swapBase` (base-first),
  `Board.mapByPileSwap` (board-first), `State.swapPiles`
  (state-first), `Move.swapM i j` (a landing's base re-anchors; a
  `reveal` at pile `a` is a `reveal` at the swapped pile; card
  arguments and card-seated bases ride along), the involutivity kit
  (`Anchor.swap_swap`, `Base.swapBase_swapBase`, `Move.swapM_swapM`,
  `State.swapPiles_swapPiles`) and the degenerate
  `State.swapPiles_self` (`swapPiles i i = id`).
* §4 **`apply_swapPiles`** — the commutation lemma:
  `apply (swapPiles st) (swapM m) = (apply st m).map (swapPiles)`,
  per engine move — defined-swapped iff defined
  (`legal_swapPiles`).  The stock/deck machinery and the heights are
  untouched by the swap, the revealed cards conjugate through
  `State.swapPiles_hiddenBase`, and the successors assemble by
  `State.swapPiles_with`.
* §5 the lift: `run_swapPiles`, `State.isWin_swapPiles`, and
  **`solvable_swapPiles_iff`** — `st.solvableFrom ↔
  (swapPiles st i j).solvableFrom` (both directions by
  involutivity), plus the engine-restricted reading
  `solvableEngine_swapPiles_iff`.  No WF premise: `apply` never
  reads the deal's *shape* clause, so the equivalences are
  state-universal.
* §6 the pristine degeneracy: at a state with every depth zero
  (`State.depthsZero`) the deal is *inert* — `reveal` is dead there
  and no other move consults the deal — so runs and solvability are
  deaf to the deal's content
  (`State.solvableFrom_setDeal_iff_of_depthsZero`).  This is the
  mechanism the wave-21 pristine-collapse witness rides.
* §7 the same-deal obstruction (`swapPiles_eq_sameDeal_forced_eq`):
  two states that share their deal can be swap-related only by the
  trivial transposition — a WF deal's pile slices have pairwise
  distinct lengths.  The mechanism of the wave-21 reachable-corner
  survival witness.

## The WF finding (recorded, not repaired)

`Deal.WF`'s shape clause is pinned to the seven *slots* (`pile a` has
`a.toIdx + 1` cards), and the seven slots have distinct sizes — so
**no nontrivial pile transposition preserves `Deal.WF`**
(`swapPiles_dealWF_blocked`): the swapped state is a coherent game
*position* (every move applies, the semantics commute, solvability
transfers — §4/§5 need nothing), but it is not a standard-deal
*shape*.  This is the structural difference between Π and the suit
fibration: `flipAll` renames slice *content* in place (lengths
preserved), while a pile transposition moves slices between
differently-sized slots.  What survives is everything else:
`State.wfsoft_swapPiles_iff` transfers the ten non-deal conjuncts of
`WF` in both directions; the deal's stock-length clause is untouched;
the flatMap distinctness of the transposed block concatenation is
this wave's open pin (no consumer needs it — a block-permutation
argument for `noDupCards` is real work this wave does not spend).
-/

/-! ## §1. The index transposition and its base action -/

/-- The anchor transposition: `i ↔ j`, every other pile fixed. -/
def Anchor.swap (i j : Anchor) : Anchor → Anchor :=
  fun a => if a = i then j else if a = j then i else a

theorem Anchor.swap_self_left (i j : Anchor) : Anchor.swap i j i = j := by
  show (if (i : Anchor) = i then j else _) = j
  rw [ite_eq_left rfl]

theorem Anchor.swap_self_right (i j : Anchor) : Anchor.swap i j j = i := by
  unfold Anchor.swap
  by_cases hij : j = i
  · rw [ite_eq_left hij]
    exact hij
  · rw [ite_eq_right hij, ite_eq_left rfl]

theorem Anchor.swap_eq_self (i j : Anchor) {a : Anchor}
    (h1 : a ≠ i) (h2 : a ≠ j) : Anchor.swap i j a = a := by
  unfold Anchor.swap
  rw [ite_eq_right h1, ite_eq_right h2]

/-- The two-arm involution: swapping twice is the identity. -/
theorem Anchor.swap_swap (i j : Anchor) (a : Anchor) :
    Anchor.swap i j (Anchor.swap i j a) = a := by
  by_cases hai : a = i
  · rw [hai, Anchor.swap_self_left, Anchor.swap_self_right]
  · by_cases haj : a = j
    · rw [haj, Anchor.swap_self_right, Anchor.swap_self_left]
    · rw [Anchor.swap_eq_self _ _ hai haj, Anchor.swap_eq_self _ _ hai haj]

/-- The degenerate transposition is the identity. -/
theorem Anchor.swap_refl (i : Anchor) (a : Anchor) :
    Anchor.swap i i a = a := by
  unfold Anchor.swap
  by_cases hai : a = i
  · rw [ite_eq_left hai, hai]
  · rw [ite_eq_right hai, ite_eq_right hai]

/-- The cross-order involution: swapping `i↔j` then `j↔i` is the
identity (the transposition is symmetric as a permutation). -/
theorem Anchor.swap_rev (i j : Anchor) (x : Anchor) :
    Anchor.swap j i (Anchor.swap i j x) = x := by
  by_cases hxi : x = i
  · rw [hxi, Anchor.swap_self_left, Anchor.swap_self_left]
  · by_cases hxj : x = j
    · rw [hxj, Anchor.swap_self_right, Anchor.swap_self_right]
    · rw [Anchor.swap_eq_self i j hxi hxj, Anchor.swap_eq_self j i hxj hxi]

/-- The numeric view is injective — distinct anchors have distinct
indices (the arithmetic of the deal-shape obstruction). -/
theorem Anchor.toIdx_inj {a a' : Anchor} (h : a.toIdx = a'.toIdx) : a = a' := by
  cases a <;> cases a' <;> simp_all [Anchor.toIdx]

/-- The base action: anchor seats re-anchor, card seats ride along. -/
def Base.swapBase (b : Base) (i j : Anchor) : Base :=
  Sum.map (Anchor.swap i j) id b

theorem Base.swapBase_inl (i j : Anchor) (a : Anchor) :
    Base.swapBase (Sum.inl a) i j = Sum.inl (Anchor.swap i j a) := rfl

theorem Base.swapBase_inr (i j : Anchor) (c : Card) :
    Base.swapBase (Sum.inr c) i j = Sum.inr c := rfl

theorem Base.swapBase_swapBase (b : Base) (i j : Anchor) :
    (b.swapBase i j).swapBase i j = b := by
  cases b with
  | inl a => rw [Base.swapBase_inl, Base.swapBase_inl, Anchor.swap_swap]
  | inr c => rw [Base.swapBase_inr, Base.swapBase_inr]

/-- Injectivity of the base action (via the involution). -/
theorem Base.swapBase_inj (_b : Base) (i j : Anchor) {b₁ b₂ : Base}
    (h : b₁.swapBase i j = b₂.swapBase i j) : b₁ = b₂ := by
  have h2 := congrArg (fun x : Base => x.swapBase i j) h
  rw [Base.swapBase_swapBase, Base.swapBase_swapBase] at h2
  exact h2

/-! ## §2. The conjugated matching -/

/-- Conjugating the matching by the transposition preserves the
matching law (involution + `bd.inj`). -/
theorem Board.mapByPileSwap_inj (bd : Board) (i j : Anchor) :
    ∀ (b₁ b₂ : Base) (c : Card),
      bd.topOf (b₁.swapBase i j) = some c →
      bd.topOf (b₂.swapBase i j) = some c → b₁ = b₂ := by
  intro b₁ b₂ c h₁ h₂
  exact Base.swapBase_inj b₁ i j (bd.inj _ _ _ h₁ h₂)

/-- The transposed board: what sat on pile `σ a`'s seat now sits on
pile `a`'s seat; card seats are untouched. -/
def Board.mapByPileSwap (bd : Board) (i j : Anchor) : Board where
  topOf := fun b => bd.topOf (b.swapBase i j)
  inj := Board.mapByPileSwap_inj bd i j

theorem mapByPileSwap_topOf (bd : Board) (i j : Anchor) (b : Base) :
    (bd.mapByPileSwap i j).topOf b = bd.topOf (b.swapBase i j) := rfl

@[simp] theorem mapByPileSwap_topOf_inr (bd : Board) (i j : Anchor) (c : Card) :
    (bd.mapByPileSwap i j).topOf (Sum.inr c) = bd.topOf (Sum.inr c) := rfl

@[simp] theorem mapByPileSwap_topOf_inl (bd : Board) (i j : Anchor) (a : Anchor) :
    (bd.mapByPileSwap i j).topOf (Sum.inl a)
      = bd.topOf (Sum.inl (Anchor.swap i j a)) := rfl

/-- The conjugated inverse search: the seat under a card moves with
the transposition. -/
theorem mapByPileSwap_bottomOf (bd : Board) (i j : Anchor) (c : Card) :
    (bd.mapByPileSwap i j).bottomOf c
      = (bd.bottomOf c).map (fun b => b.swapBase i j) := by
  cases hb : bd.bottomOf c with
  | none =>
      refine (Board.bottomOf_eq_none _ c).mpr (fun b' hb' => ?_)
      rw [mapByPileSwap_topOf] at hb'
      have hbb := (Board.bottomOf_eq bd c (b'.swapBase i j)).mpr hb'
      rw [hb] at hbb
      exact absurd hbb (by simp)
  | some b =>
      show (bd.mapByPileSwap i j).bottomOf c = some (b.swapBase i j)
      refine (Board.bottomOf_eq _ c _).mpr ?_
      show (bd.mapByPileSwap i j).topOf (b.swapBase i j) = _
      rw [mapByPileSwap_topOf, Base.swapBase_swapBase]
      exact (Board.bottomOf_eq bd c b).mp hb

theorem mapByPileSwap_attach (bd : Board) (i j : Anchor) {b : Base} {c : Card}
    {bd' : Board} (hatt : bd.attach b c = some bd') :
    (bd.mapByPileSwap i j).attach (b.swapBase i j) c
      = some (bd'.mapByPileSwap i j) := by
  have hne : bd.attach b c ≠ none := by rw [hatt]; simp
  obtain ⟨htop, hbot⟩ := (Board.attach_eq_some_iff bd b c).mp hne
  have htopR : (bd.mapByPileSwap i j).topOf (b.swapBase i j) = none := by
    rw [mapByPileSwap_topOf, Base.swapBase_swapBase]
    exact htop
  have hbotR : (bd.mapByPileSwap i j).bottomOf c = none := by
    rw [mapByPileSwap_bottomOf, hbot]
    rfl
  have hneR : (bd.mapByPileSwap i j).attach (b.swapBase i j) c ≠ none :=
    Board.attach_eq_some_iff _ _ _ |>.mpr ⟨htopR, hbotR⟩
  cases hR : (bd.mapByPileSwap i j).attach (b.swapBase i j) c with
  | none => rw [hR] at hneR; exact absurd hneR (by simp)
  | some bdR =>
      rw [Option.some.injEq]
      refine Board.ext_topOf (funext (fun b'' => ?_))
      by_cases hbb : b'' = b.swapBase i j
      · rw [hbb, Board.attach_topOf _ _ _ hR]
        show some c = (bd'.mapByPileSwap i j).topOf (b.swapBase i j)
        rw [mapByPileSwap_topOf, Base.swapBase_swapBase, Board.attach_topOf _ _ _ hatt]
      · rw [Board.attach_topOf_ne _ _ _ hR hbb]
        show (bd.mapByPileSwap i j).topOf b''
          = (bd'.mapByPileSwap i j).topOf b''
        have hcb : b''.swapBase i j ≠ b := by
          intro hcon
          have hc2 := congrArg (fun x : Base => x.swapBase i j) hcon
          rw [Base.swapBase_swapBase] at hc2
          exact hbb hc2
        rw [mapByPileSwap_topOf, mapByPileSwap_topOf,
          Board.attach_topOf_ne _ _ _ hatt hcb]

theorem mapByPileSwap_detach (bd : Board) (i j : Anchor) (b : Base) :
    (bd.mapByPileSwap i j).detach (b.swapBase i j)
      = (bd.detach b).mapByPileSwap i j := by
  refine Board.ext_topOf (funext (fun b'' => ?_))
  by_cases hbb : b'' = b.swapBase i j
  · rw [hbb]
    show (if b.swapBase i j = b.swapBase i j then none
        else (bd.mapByPileSwap i j).topOf (b.swapBase i j))
      = ((bd.detach b).mapByPileSwap i j).topOf (b.swapBase i j)
    rw [ite_eq_left rfl, mapByPileSwap_topOf, Base.swapBase_swapBase,
      Board.detach_topOf]
  · show (if b'' = b.swapBase i j then none
        else (bd.mapByPileSwap i j).topOf b'')
      = ((bd.detach b).mapByPileSwap i j).topOf b''
    rw [ite_eq_right hbb]
    have hcb : b''.swapBase i j ≠ b := by
      intro hcon
      have hc2 := congrArg (fun x : Base => x.swapBase i j) hcon
      rw [Base.swapBase_swapBase] at hc2
      exact hbb hc2
    rw [mapByPileSwap_topOf, mapByPileSwap_topOf,
      Board.detach_topOf_ne _ _ _ hcb]

/-- The walk above a card is untouched: it reads only card seats. -/
theorem mapByPileSwap_aboveOf (bd : Board) (i j : Anchor) (c : Card) :
    (bd.mapByPileSwap i j).aboveOf c = bd.aboveOf c :=
  Board.aboveOf_congr (fun _ _ => rfl)

/-- The inverse form of the detach conjugation, at the swapped
witness (the pilePile arms need detach at `bR`, not at `σB bR`). -/
theorem mapByPileSwap_detach_inv (bd : Board) (i j : Anchor) (b : Base) :
    (bd.mapByPileSwap i j).detach b
      = (bd.detach (b.swapBase i j)).mapByPileSwap i j := by
  have h := mapByPileSwap_detach bd i j (b.swapBase i j)
  rw [Base.swapBase_swapBase] at h
  exact h

theorem Base.swapBase_rev (b : Base) (i j : Anchor) :
    (b.swapBase i j).swapBase j i = b := by
  cases b with
  | inl x => rw [Base.swapBase_inl, Base.swapBase_inl, Anchor.swap_rev]
  | inr c => rfl

theorem Board.mapByPileSwap_rev (bd : Board) (i j : Anchor) :
    (bd.mapByPileSwap i j).mapByPileSwap j i = bd := by
  refine Board.ext_topOf (funext (fun b => ?_))
  show bd.topOf ((b.swapBase j i).swapBase i j) = bd.topOf b
  rw [Base.swapBase_rev]

/-! ## §3. The state action and the move co-action -/

/-- The pile transposition on states: swap the two deal slices (the
hidden stacks follow — slice and boundary depth travel together),
the depths, and the anchor seats of the matching.  Heights, the
stock cycle and the draw step stay fixed: the piles' content moves,
the rest of the game does not. -/
def State.swapPiles (st : State) (i j : Anchor) : State :=
  { st with
    deal := { piles := fun a => st.deal.piles (Anchor.swap i j a),
              stock := st.deal.stock },
    board := st.board.mapByPileSwap i j,
    depths := fun a => st.depths (Anchor.swap i j a) }

theorem State.swapPiles_swapPiles (st : State) (i j : Anchor) :
    (st.swapPiles i j).swapPiles i j = st := by
  refine state_ext ?_ ?_ rfl ?_ rfl rfl
  · apply Deal.ext'
    · intro a
      show st.deal.piles (Anchor.swap i j (Anchor.swap i j a)) = st.deal.piles a
      rw [Anchor.swap_swap]
    · show st.deal.stock = st.deal.stock
      rfl
  · show (st.board.mapByPileSwap i j).mapByPileSwap i j = st.board
    refine Board.ext_topOf (funext (fun b => ?_))
    show st.board.topOf ((b.swapBase i j).swapBase i j) = st.board.topOf b
    rw [Base.swapBase_swapBase]
  · funext a
    show st.depths (Anchor.swap i j (Anchor.swap i j a)) = st.depths a
    rw [Anchor.swap_swap]

/-- The degenerate transposition is the identity on states. -/
theorem State.swapPiles_self (st : State) (i : Anchor) :
    st.swapPiles i i = st := by
  refine state_ext ?_ ?_ rfl ?_ rfl rfl
  · apply Deal.ext'
    · intro a
      show st.deal.piles (Anchor.swap i i a) = st.deal.piles a
      rw [Anchor.swap_refl]
    · show st.deal.stock = st.deal.stock
      rfl
  · refine Board.ext_topOf (funext (fun b => ?_))
    show st.board.topOf (b.swapBase i i) = st.board.topOf b
    cases b with
    | inl a => rw [Base.swapBase_inl, Anchor.swap_refl]
    | inr c => rw [Base.swapBase_inr]
  · funext a
    show st.depths (Anchor.swap i i a) = st.depths a
    rw [Anchor.swap_refl]

@[simp] theorem State.swapPiles_deal_piles (st : State) (i j : Anchor) (a : Anchor) :
    (st.swapPiles i j).deal.piles a = st.deal.piles (Anchor.swap i j a) := rfl

@[simp] theorem State.swapPiles_deal_stock (st : State) (i j : Anchor) :
    (st.swapPiles i j).deal.stock = st.deal.stock := rfl

@[simp] theorem State.swapPiles_depths (st : State) (i j : Anchor) (a : Anchor) :
    (st.swapPiles i j).depths a = st.depths (Anchor.swap i j a) := rfl

@[simp] theorem State.swapPiles_heights (st : State) (i j : Anchor) :
    (st.swapPiles i j).heights = st.heights := rfl

@[simp] theorem State.swapPiles_stock (st : State) (i j : Anchor) :
    (st.swapPiles i j).stock = st.stock := rfl

@[simp] theorem State.swapPiles_drawStep (st : State) (i j : Anchor) :
    (st.swapPiles i j).drawStep = st.drawStep := rfl

/-- The hidden stack of the swapped pile is the swapped-pile slice. -/
theorem State.swapPiles_hidden (st : State) (i j : Anchor) (a : Anchor) :
    (st.swapPiles i j).hidden a = st.hidden (Anchor.swap i j a) := rfl

theorem State.swapPiles_topHidden (st : State) (i j : Anchor) (a : Anchor) :
    (st.swapPiles i j).topHidden a = st.topHidden (Anchor.swap i j a) := by
  show ((st.swapPiles i j).hidden a).getLast? = (st.hidden (Anchor.swap i j a)).getLast?
  rw [State.swapPiles_hidden]

theorem State.hiddenBase_cases {st : State} {a : Anchor} {d : Card}
    (h : ((st.hidden a).reverse.drop 1).head? = some d) :
    st.hiddenBase a = Sum.inr d := by
  show (match ((st.hidden a).reverse.drop 1).head? with
        | some d' => Sum.inr d'
        | none => Sum.inl a) = Sum.inr d
  rw [h]

theorem State.hiddenBase_cases_none {st : State} {a : Anchor}
    (h : ((st.hidden a).reverse.drop 1).head? = none) :
    st.hiddenBase a = Sum.inl a := by
  show (match ((st.hidden a).reverse.drop 1).head? with
        | some d' => Sum.inr d'
        | none => Sum.inl a) = Sum.inl a
  rw [h]

/-- The reveal base of the swapped pile is the swapped-base image. -/
theorem State.swapPiles_hiddenBase (st : State) (i j : Anchor) (a : Anchor) :
    (st.swapPiles i j).hiddenBase a
      = Base.swapBase (st.hiddenBase (Anchor.swap i j a)) i j := by
  cases hhead : ((st.hidden (Anchor.swap i j a)).reverse.drop 1).head? with
  | some d =>
      have hL : (((st.swapPiles i j).hidden a).reverse.drop 1).head? = some d :=
        hhead
      rw [State.hiddenBase_cases hL, State.hiddenBase_cases hhead,
        Base.swapBase_inr]
  | none =>
      have hL : (((st.swapPiles i j).hidden a).reverse.drop 1).head? = none :=
        hhead
      rw [State.hiddenBase_cases_none hL, State.hiddenBase_cases_none hhead,
        Base.swapBase_inl, Anchor.swap_swap]

theorem State.swapPiles_board (st : State) (i j : Anchor) :
    (st.swapPiles i j).board = st.board.mapByPileSwap i j := rfl

theorem State.swapPiles_board_topOf (st : State) (i j : Anchor) (b : Base) :
    (st.swapPiles i j).board.topOf b = st.board.topOf (b.swapBase i j) := rfl

theorem State.swapPiles_bottomOf (st : State) (i j : Anchor) (c : Card) :
    (st.swapPiles i j).board.bottomOf c
      = (st.board.bottomOf c).map (fun b => b.swapBase i j) :=
  mapByPileSwap_bottomOf st.board i j c

theorem State.swapPiles_aboveOf (st : State) (i j : Anchor) (c : Card) :
    (st.swapPiles i j).board.aboveOf c = st.board.aboveOf c :=
  mapByPileSwap_aboveOf st.board i j c

theorem State.swapPiles_isVis (st : State) (i j : Anchor) (d : Card) :
    (st.swapPiles i j).isVis d = st.isVis d := by
  simp only [State.isVis]
  rw [State.swapPiles_bottomOf]
  cases st.board.bottomOf d with
  | none => rfl
  | some b => rfl

theorem State.swapPiles_canPlace (st : State) (i j : Anchor) (c : Card) (b : Base) :
    (st.swapPiles i j).canPlace c b
      = st.canPlace c (b.swapBase i j) := by
  cases b with
  | inl a => rfl
  | inr d =>
      show (decide (st.board.topOf (Sum.inr d) = none)
              && ((st.swapPiles i j).isVis d && canSitOn c d))
        = (decide (st.board.topOf (Sum.inr d) = none)
            && (st.isVis d && canSitOn c d))
      rw [State.swapPiles_isVis]

theorem State.swapPiles_canMoveRun (st : State) (i j : Anchor) (c : Card) (b : Base) :
    (st.swapPiles i j).canMoveRun c b
      = st.canMoveRun c (b.swapBase i j) := by
  cases b with
  | inl a =>
      show ((st.swapPiles i j).canPlace c (Sum.inl a) && true)
        = (st.canPlace c (Sum.inl (Anchor.swap i j a)) && true)
      rw [State.swapPiles_canPlace, Base.swapBase_inl]
  | inr d =>
      show ((st.swapPiles i j).canPlace c (Sum.inr d)
              && !((st.swapPiles i j).board.aboveOf c).contains d)
        = (st.canPlace c (Sum.inr d) && !(st.board.aboveOf c).contains d)
      rw [State.swapPiles_canPlace, Base.swapBase_inr, State.swapPiles_aboveOf]

/-- The move co-action: a landing's base re-anchors, a `reveal` at
pile `a` is a `reveal` at the swapped pile; card arguments and every
card-seated base ride along untouched. -/
def Move.swapM (i j : Anchor) : Move → Move
  | .draw => .draw
  | .reveal a => .reveal (Anchor.swap i j a)
  | .deckPile c b => .deckPile c (b.swapBase i j)
  | .deckStack c => .deckStack c
  | .pileStack c => .pileStack c
  | .stackPile c b => .stackPile c (b.swapBase i j)
  | .pilePile c b => .pilePile c (b.swapBase i j)

theorem Move.swapM_swapM (i j : Anchor) (m : Move) :
    Move.swapM i j (Move.swapM i j m) = m := by
  cases m with
  | draw => rfl
  | reveal a =>
      show Move.reveal (Anchor.swap i j (Anchor.swap i j a)) = _
      rw [Anchor.swap_swap]
  | deckPile c b =>
      show Move.deckPile c ((b.swapBase i j).swapBase i j) = _
      rw [Base.swapBase_swapBase]
  | deckStack c => rfl
  | pileStack c => rfl
  | stackPile c b =>
      show Move.stackPile c ((b.swapBase i j).swapBase i j) = _
      rw [Base.swapBase_swapBase]
  | pilePile c b =>
      show Move.pilePile c ((b.swapBase i j).swapBase i j) = _
      rw [Base.swapBase_swapBase]

theorem swapM_isEngine (i j : Anchor) (m : Move) :
    (Move.swapM i j m).isEngine = m.isEngine := by
  cases m <;> rfl

/-- Successors conjugate componentwise (the arm-assembly workhorse). -/
theorem State.swapPiles_with (st : State) (i j : Anchor) (bd : Board)
    (hs : Suit → Nat) (dpt : Anchor → Nat) (cy : Cycle Card) :
    ({ st with board := bd, heights := hs, depths := dpt, stock := cy }).swapPiles i j
      = { st.swapPiles i j with
          board := bd.mapByPileSwap i j,
          heights := hs,
          depths := fun a => dpt (Anchor.swap i j a),
          stock := cy } := rfl

/-! ## §4. The conjugation theorem -/

/-- **The commutation lemma**: applying the swapped move to the
swapped state is applying the move to the state, swapped — for every
engine move at once (defined-swapped iff defined, both sides of the
`Option` oracle; see `legal_swapPiles` below).  No WF premise: the
engine ignores the deal's shape clause, and the stock/deck machinery
and the heights are untouched by the swap. -/
theorem apply_swapPiles (i j : Anchor) (m : Move) (st : State) :
    (st.swapPiles i j).apply (Move.swapM i j m)
      = (st.apply m).map (fun s => s.swapPiles i j) := by
  cases m with
  | draw =>
      show (st.swapPiles i j).apply Move.draw
        = (st.apply Move.draw).map (fun s => s.swapPiles i j)
      cases hst : st.apply Move.draw with
      | none =>
          have h : st.applyDraw ≠ none := by simp [State.applyDraw]
          rw [show st.apply (Move.draw) = st.applyDraw from rfl] at hst
          exact absurd hst h
      | some st' =>
          rw [apply_draw_iff] at hst
          obtain ⟨rfl⟩ := hst
          show some { st.swapPiles i j with
              stock := (st.swapPiles i j).stock.dealOnce (st.swapPiles i j).drawStep }
            = (some { st with stock := st.stock.dealOnce st.drawStep }).map
              (fun s => s.swapPiles i j)
          rw [Option.map_some]
          refine congrArg some (state_ext rfl rfl rfl rfl rfl rfl)
  | reveal a =>
      show (st.swapPiles i j).apply (Move.reveal (Anchor.swap i j a))
        = (st.apply (Move.reveal a)).map (fun s => s.swapPiles i j)
      cases hst : st.apply (Move.reveal a) with
      | none =>
          show (st.swapPiles i j).apply (Move.reveal (Anchor.swap i j a)) = none
          cases hR : (st.swapPiles i j).apply (Move.reveal (Anchor.swap i j a)) with
          | none => rfl
          | some s'' =>
              exfalso
              rw [apply_reveal_iff] at hR
              obtain ⟨r, bdR, htopR, hbareR, hattR, -⟩ := hR
              have htop : st.topHidden a = some r := by
                rw [State.swapPiles_topHidden, Anchor.swap_swap] at htopR
                exact htopR
              have hbare : st.board.topOf (Sum.inr r) = none := hbareR
              rw [State.swapPiles_hiddenBase, Anchor.swap_swap] at hattR
              obtain ⟨htop2, hbot2⟩ := (Board.attach_eq_some_iff _ _ _).mp (by
                rw [hattR]; simp)
              rw [State.swapPiles_board_topOf, Base.swapBase_swapBase] at htop2
              rw [State.swapPiles_bottomOf] at hbot2
              have hbot3 : st.board.bottomOf r = none :=
                Option.map_eq_none_iff.mp hbot2
              have hneS : st.board.attach (st.hiddenBase a) r ≠ none :=
                Board.attach_eq_some_iff _ _ _ |>.mpr ⟨htop2, hbot3⟩
              cases hS : st.board.attach (st.hiddenBase a) r with
              | none => rw [hS] at hneS; exact absurd hneS (by simp)
              | some bd₀ =>
                  exact absurd (apply_reveal_iff.mpr
                    ⟨r, bd₀, htop, hbare, hS, rfl⟩) (by rw [hst]; simp)
      | some st' =>
          rw [apply_reveal_iff] at hst
          obtain ⟨r, bd, htop, hbare, hatt, hst'⟩ := hst
          show (st.swapPiles i j).apply (Move.reveal (Anchor.swap i j a))
            = some (st'.swapPiles i j)
          rw [apply_reveal_iff]
          have htopR : (st.swapPiles i j).topHidden (Anchor.swap i j a) = some r := by
            rw [State.swapPiles_topHidden, Anchor.swap_swap, htop]
          have hbareR : (st.swapPiles i j).board.topOf (Sum.inr r) = none := hbare
          have hattR : (st.swapPiles i j).board.attach
              ((st.hiddenBase a).swapBase i j) r
              = some (bd.mapByPileSwap i j) := by
            have h2 := mapByPileSwap_attach st.board i j hatt
            rw [← State.swapPiles_board] at h2
            exact h2
          refine ⟨r, bd.mapByPileSwap i j, htopR, hbareR, ?_, ?_⟩
          · rw [State.swapPiles_hiddenBase, Anchor.swap_swap]
            exact hattR
          · rw [hst']
            refine state_ext rfl rfl ?_ ?_ rfl rfl
            · exact (State.swapPiles_heights st i j).symm
            · funext x
              show (if Anchor.swap i j x = a then st.depths a - 1
                    else st.depths (Anchor.swap i j x))
                = (if x = Anchor.swap i j a
                    then (st.swapPiles i j).depths (Anchor.swap i j a) - 1
                    else (st.swapPiles i j).depths x)
              by_cases hx : x = Anchor.swap i j a
              · have h1 : Anchor.swap i j x = a := by
                  have h2 := congrArg (Anchor.swap i j) hx
                  rw [Anchor.swap_swap] at h2
                  exact h2
                rw [ite_eq_left h1, ite_eq_left hx, State.swapPiles_depths,
                  Anchor.swap_swap]
              · have h1 : Anchor.swap i j x ≠ a := by
                  intro hcon
                  have h2 := congrArg (Anchor.swap i j) hcon
                  rw [Anchor.swap_swap] at h2
                  exact hx h2
                rw [ite_eq_right h1, ite_eq_right hx, State.swapPiles_depths]
  | deckPile c b =>
      show (st.swapPiles i j).apply (Move.deckPile c (b.swapBase i j))
        = (st.apply (Move.deckPile c b)).map (fun s => s.swapPiles i j)
      have hcp : (st.swapPiles i j).canPlace c (b.swapBase i j)
          = st.canPlace c b := by
        rw [State.swapPiles_canPlace, Base.swapBase_swapBase]
      cases hst : st.apply (Move.deckPile c b) with
      | none =>
          show (st.swapPiles i j).apply (Move.deckPile c (b.swapBase i j)) = none
          cases hR : (st.swapPiles i j).apply (Move.deckPile c (b.swapBase i j)) with
          | none => rfl
          | some s'' =>
              exfalso
              rw [apply_deckPile_iff] at hR
              obtain ⟨hpR, hcpR, bdR, hattR, -⟩ := hR
              rw [hcp] at hcpR
              have hp : st.stock.prev = some c := hpR
              obtain ⟨htopR, hbotR⟩ := (Board.attach_eq_some_iff _ _ _).mp (by
                rw [hattR]; simp)
              rw [State.swapPiles_board_topOf, Base.swapBase_swapBase] at htopR
              rw [State.swapPiles_bottomOf] at hbotR
              have hneS : st.board.attach b c ≠ none :=
                Board.attach_eq_some_iff _ _ _ |>.mpr
                  ⟨htopR, Option.map_eq_none_iff.mp hbotR⟩
              cases hS : st.board.attach b c with
              | none => rw [hS] at hneS; exact absurd hneS (by simp)
              | some bd₀ =>
                  exact absurd (apply_deckPile_iff.mpr ⟨hp, hcpR, bd₀, hS, rfl⟩)
                    (by rw [hst]; simp)
      | some st' =>
          rw [apply_deckPile_iff] at hst
          obtain ⟨hp, hcp', bd, hatt, hst'⟩ := hst
          show (st.swapPiles i j).apply (Move.deckPile c (b.swapBase i j))
            = some (st'.swapPiles i j)
          rw [apply_deckPile_iff]
          have hattR : (st.swapPiles i j).board.attach (b.swapBase i j) c
              = some (bd.mapByPileSwap i j) := by
            have h2 := mapByPileSwap_attach st.board i j hatt
            rw [← State.swapPiles_board] at h2
            exact h2
          refine ⟨hp, by rw [hcp]; exact hcp', bd.mapByPileSwap i j, hattR, ?_⟩
          rw [hst']
          exact state_ext rfl rfl rfl rfl rfl rfl
  | deckStack c =>
      show (st.swapPiles i j).apply (Move.deckStack c)
        = (st.apply (Move.deckStack c)).map (fun s => s.swapPiles i j)
      cases hst : st.apply (Move.deckStack c) with
      | none =>
          show (st.swapPiles i j).apply (Move.deckStack c) = none
          cases hR : (st.swapPiles i j).apply (Move.deckStack c) with
          | none => rfl
          | some s'' =>
              exfalso
              rw [apply_deckStack_iff] at hR
              obtain ⟨hpR, hrkR, -⟩ := hR
              have hp : st.stock.prev = some c := hpR
              have hrk : c.rank.toIdx = st.heights c.suit := hrkR
              exact absurd (apply_deckStack_iff.mpr ⟨hp, hrk, rfl⟩)
                (by rw [hst]; simp)
      | some st' =>
          rw [apply_deckStack_iff] at hst
          obtain ⟨hp, hrk, hst'⟩ := hst
          show (st.swapPiles i j).apply (Move.deckStack c) = some (st'.swapPiles i j)
          rw [apply_deckStack_iff]
          refine ⟨hp, hrk, ?_⟩
          rw [hst']
          exact state_ext rfl rfl rfl rfl rfl rfl
  | pileStack c =>
      show (st.swapPiles i j).apply (Move.pileStack c)
        = (st.apply (Move.pileStack c)).map (fun s => s.swapPiles i j)
      cases hst : st.apply (Move.pileStack c) with
      | none =>
          show (st.swapPiles i j).apply (Move.pileStack c) = none
          cases hR : (st.swapPiles i j).apply (Move.pileStack c) with
          | none => rfl
          | some s'' =>
              exfalso
              rw [apply_pileStack_iff] at hR
              obtain ⟨htR, b, hbR, hrkR, -⟩ := hR
              have htop : st.board.topOf (Sum.inr c) = none := htR
              have hbot : st.board.bottomOf c = some (b.swapBase i j) := by
                rw [State.swapPiles_bottomOf] at hbR
                cases hbb : st.board.bottomOf c with
                | none => rw [hbb] at hbR; exact absurd hbR (by simp)
                | some bx =>
                    rw [hbb] at hbR
                    rw [Option.map_some, Option.some.injEq] at hbR
                    have hbx := congrArg (fun x : Base => x.swapBase i j) hbR
                    rw [Base.swapBase_swapBase] at hbx
                    rw [hbx]
              exact absurd (apply_pileStack_iff.mpr
                ⟨htop, b.swapBase i j, hbot, hrkR, rfl⟩) (by rw [hst]; simp)
      | some st' =>
          rw [apply_pileStack_iff] at hst
          obtain ⟨htop, b, hb, hrk, hst'⟩ := hst
          show (st.swapPiles i j).apply (Move.pileStack c) = some (st'.swapPiles i j)
          rw [apply_pileStack_iff]
          have hbotR : (st.swapPiles i j).board.bottomOf c
              = some (b.swapBase i j) := by
            rw [State.swapPiles_bottomOf, hb]
            rfl
          refine ⟨htop, b.swapBase i j, hbotR, hrk, ?_⟩
          rw [hst']
          have hdet : (st.swapPiles i j).board.detach (b.swapBase i j)
              = (st.board.detach b).mapByPileSwap i j :=
            mapByPileSwap_detach st.board i j b
          rw [hdet]
          exact state_ext rfl rfl rfl rfl rfl rfl
  | stackPile c b =>
      show (st.swapPiles i j).apply (Move.stackPile c (b.swapBase i j))
        = (st.apply (Move.stackPile c b)).map (fun s => s.swapPiles i j)
      have hcp : (st.swapPiles i j).canPlace c (b.swapBase i j)
          = st.canPlace c b := by
        rw [State.swapPiles_canPlace, Base.swapBase_swapBase]
      cases hst : st.apply (Move.stackPile c b) with
      | none =>
          show (st.swapPiles i j).apply (Move.stackPile c (b.swapBase i j)) = none
          cases hR : (st.swapPiles i j).apply (Move.stackPile c (b.swapBase i j)) with
          | none => rfl
          | some s'' =>
              exfalso
              rw [apply_stackPile_iff] at hR
              obtain ⟨hrkR, hcpR, bdR, hattR, -⟩ := hR
              rw [hcp] at hcpR
              have hrk : c.rank.toIdx + 1 = st.heights c.suit := hrkR
              have hcp2 : st.canPlace c b = true := hcpR
              obtain ⟨htopR, hbotR⟩ := (Board.attach_eq_some_iff _ _ _).mp (by
                rw [hattR]; simp)
              rw [State.swapPiles_board_topOf, Base.swapBase_swapBase] at htopR
              rw [State.swapPiles_bottomOf] at hbotR
              have hneS : st.board.attach b c ≠ none :=
                Board.attach_eq_some_iff _ _ _ |>.mpr
                  ⟨htopR, Option.map_eq_none_iff.mp hbotR⟩
              cases hS : st.board.attach b c with
              | none => rw [hS] at hneS; exact absurd hneS (by simp)
              | some bd₀ =>
                  exact absurd (apply_stackPile_iff.mpr ⟨hrk, hcp2, bd₀, hS, rfl⟩)
                    (by rw [hst]; simp)
      | some st' =>
          rw [apply_stackPile_iff] at hst
          obtain ⟨hrk, hcp', bd, hatt, hst'⟩ := hst
          show (st.swapPiles i j).apply (Move.stackPile c (b.swapBase i j))
            = some (st'.swapPiles i j)
          rw [apply_stackPile_iff]
          have hattR : (st.swapPiles i j).board.attach (b.swapBase i j) c
              = some (bd.mapByPileSwap i j) := by
            have h2 := mapByPileSwap_attach st.board i j hatt
            rw [← State.swapPiles_board] at h2
            exact h2
          refine ⟨hrk, by rw [hcp]; exact hcp', bd.mapByPileSwap i j, hattR, ?_⟩
          rw [hst']
          exact state_ext rfl rfl rfl rfl rfl rfl
  | pilePile c b =>
      show (st.swapPiles i j).apply (Move.pilePile c (b.swapBase i j))
        = (st.apply (Move.pilePile c b)).map (fun s => s.swapPiles i j)
      cases hst : st.apply (Move.pilePile c b) with
      | none =>
          show (st.swapPiles i j).apply (Move.pilePile c (b.swapBase i j)) = none
          cases hR : (st.swapPiles i j).apply (Move.pilePile c (b.swapBase i j)) with
          | none => rfl
          | some s'' =>
              exfalso
              rw [apply_pilePile_iff] at hR
              obtain ⟨bR, hbR, hneR, hcmrR, bdR, hattR, -⟩ := hR
              have hb : st.board.bottomOf c = some (bR.swapBase i j) := by
                rw [State.swapPiles_bottomOf] at hbR
                cases hbb : st.board.bottomOf c with
                | none => rw [hbb] at hbR; exact absurd hbR (by simp)
                | some bx =>
                    rw [hbb] at hbR
                    rw [Option.map_some, Option.some.injEq] at hbR
                    have hbx := congrArg (fun x : Base => x.swapBase i j) hbR
                    rw [Base.swapBase_swapBase] at hbx
                    rw [hbx]
              have hne : bR.swapBase i j ≠ b := by
                intro hcon
                have h2 := congrArg (fun x : Base => x.swapBase i j) hcon
                rw [Base.swapBase_swapBase] at h2
                exact hneR h2
              have hcmr : st.canMoveRun c b = true := by
                have h := State.swapPiles_canMoveRun st i j c (b.swapBase i j)
                rw [Base.swapBase_swapBase] at h
                rwa [h] at hcmrR
              obtain ⟨htopR, hbotR⟩ := (Board.attach_eq_some_iff _ _ _).mp (by
                rw [hattR]; simp)
              have hdet : (st.swapPiles i j).board.detach bR
                  = (st.board.detach (bR.swapBase i j)).mapByPileSwap i j :=
                mapByPileSwap_detach_inv st.board i j bR
              rw [hdet, mapByPileSwap_topOf, Base.swapBase_swapBase] at htopR
              rw [hdet, mapByPileSwap_bottomOf] at hbotR
              have hbot3 : (st.board.detach (bR.swapBase i j)).bottomOf c = none :=
                Option.map_eq_none_iff.mp hbotR
              have hneS : (st.board.detach (bR.swapBase i j)).attach b c ≠ none :=
                Board.attach_eq_some_iff _ _ _ |>.mpr ⟨htopR, hbot3⟩
              cases hS : (st.board.detach (bR.swapBase i j)).attach b c with
              | none => rw [hS] at hneS; exact absurd hneS (by simp)
              | some bd₀ =>
                  exact absurd (apply_pilePile_iff.mpr
                    ⟨bR.swapBase i j, hb, hne, hcmr, bd₀, hS, rfl⟩) (by rw [hst]; simp)
      | some st' =>
          rw [apply_pilePile_iff] at hst
          obtain ⟨b₀, hb, hne, hcmr, bd, hatt, hst'⟩ := hst
          show (st.swapPiles i j).apply (Move.pilePile c (b.swapBase i j))
            = some (st'.swapPiles i j)
          rw [apply_pilePile_iff]
          have hbR : (st.swapPiles i j).board.bottomOf c
              = some (b₀.swapBase i j) := by
            rw [State.swapPiles_bottomOf, hb]
            rfl
          have hneR : b₀.swapBase i j ≠ b.swapBase i j :=
            fun hcon => hne (Base.swapBase_inj b₀ i j hcon)
          have hcmrR : (st.swapPiles i j).canMoveRun c (b.swapBase i j) = true := by
            rw [State.swapPiles_canMoveRun, Base.swapBase_swapBase]
            exact hcmr
          have hattR : ((st.swapPiles i j).board.detach (b₀.swapBase i j)).attach
              (b.swapBase i j) c = some (bd.mapByPileSwap i j) := by
            have hdet : (st.swapPiles i j).board.detach (b₀.swapBase i j)
                = (st.board.detach b₀).mapByPileSwap i j :=
              mapByPileSwap_detach st.board i j b₀
            rw [hdet]
            exact mapByPileSwap_attach (st.board.detach b₀) i j hatt
          refine ⟨b₀.swapBase i j, hbR, hneR, hcmrR, bd.mapByPileSwap i j, hattR, ?_⟩
          rw [hst']
          exact state_ext rfl rfl rfl rfl rfl rfl

/-- Legality conjugates (defined-swapped iff defined). -/
theorem legal_swapPiles (i j : Anchor) (st : State) (m : Move) :
    (st.swapPiles i j).legal (Move.swapM i j m) = st.legal m := by
  simp only [State.legal]
  rw [apply_swapPiles]
  cases st.apply m with
  | none => rfl
  | some st' => rfl

/-! ## §5. The lift: runs and solvability -/

theorem State.isWin_swapPiles (st : State) (i j : Anchor) :
    (st.swapPiles i j).isWin = st.isWin := rfl

theorem run_swapPiles (i j : Anchor) : ∀ (st : State) (play : List Move),
    (st.swapPiles i j).run (play.map (Move.swapM i j))
      = (st.run play).map (fun (s : State) => s.swapPiles i j) := by
  intro st play
  revert st
  induction play with
  | nil => intro st; rfl
  | cons m ms ih =>
      intro st
      show (match (st.swapPiles i j).apply (Move.swapM i j m) with
            | some s' => s'.run (ms.map (Move.swapM i j))
            | none => none)
        = (match st.apply m with
            | some s' => s'.run ms
            | none => none).map (fun (s : State) => s.swapPiles i j)
      rw [apply_swapPiles i j m st]
      cases hst : st.apply m with
      | none => rfl
      | some st' => exact ih st'

theorem solvable_of_swapPiles {i j : Anchor} {st : State}
    (h : st.solvableFrom) : (st.swapPiles i j).solvableFrom := by
  obtain ⟨play, w, hrun, hwin⟩ := h
  refine ⟨play.map (Move.swapM i j), w.swapPiles i j, ?_, ?_⟩
  · rw [run_swapPiles i j st play, hrun]
    rfl
  · rw [State.isWin_swapPiles]
    exact hwin

/-- **THE THEOREM** — the game is equi-solvable under permuting whole
tableau piles (hidden stacks included): solvability is invariant
under the pile transposition, both directions by involutivity.  No
WF premise — the commutation is state-universal. -/
theorem solvable_swapPiles_iff (i j : Anchor) (st : State) :
    st.solvableFrom ↔ (st.swapPiles i j).solvableFrom := by
  constructor
  · exact fun h => solvable_of_swapPiles h
  · intro h
    have h2 := solvable_of_swapPiles (i := i) (j := j) h
    rwa [State.swapPiles_swapPiles] at h2

theorem solvableEngine_of_swapPiles {i j : Anchor} {st : State}
    (h : st.solvableEngine) : (st.swapPiles i j).solvableEngine := by
  obtain ⟨play, heng, w, hrun, hwin⟩ := h
  refine ⟨play.map (Move.swapM i j), ?_, w.swapPiles i j, ?_, ?_⟩
  · intro m hm
    obtain ⟨m₀, hm₀, heq⟩ := List.mem_map.mp hm
    rw [← heq, swapM_isEngine]
    exact heng m₀ hm₀
  · rw [run_swapPiles i j st play, hrun]
    rfl
  · rw [State.isWin_swapPiles]
    exact hwin

/-- The engine-restricted reading of the same invariance. -/
theorem solvableEngine_swapPiles_iff (i j : Anchor) (st : State) :
    st.solvableEngine ↔ (st.swapPiles i j).solvableEngine := by
  constructor
  · exact fun h => solvableEngine_of_swapPiles h
  · intro h
    have h2 := solvableEngine_of_swapPiles (i := i) (j := j) h
    rwa [State.swapPiles_swapPiles] at h2

/-! ## §6. The pristine degeneracy: all-hidden-empty states -/

/-- A state whose hidden stacks are all empty (every depth zero).  No
`reveal` can ever fire here, and no other move consults the deal. -/
def State.depthsZero (st : State) : Prop := ∀ a, st.depths a = 0

theorem State.depthsZero_topHidden {st : State} (hz : st.depthsZero) (a : Anchor) :
    st.topHidden a = none := by
  show ((st.deal.piles a).take (st.depths a)).getLast? = none
  rw [hz a, List.take_zero]
  rfl

theorem State.depthsZero_apply {st st' : State} {m : Move}
    (h : st.apply m = some st') (hz : st.depthsZero) : st'.depthsZero := by
  cases m with
  | draw =>
      rw [apply_draw_iff] at h
      obtain ⟨rfl⟩ := h
      exact hz
  | reveal a =>
      rw [apply_reveal_iff] at h
      obtain ⟨r, bd, htop, -, -, -⟩ := h
      rw [State.depthsZero_topHidden hz a] at htop
      exact absurd htop (by simp)
  | deckPile c b =>
      rw [apply_deckPile_iff] at h
      obtain ⟨-, -, -, -, rfl⟩ := h
      exact hz
  | deckStack c =>
      rw [apply_deckStack_iff] at h
      obtain ⟨-, -, rfl⟩ := h
      exact hz
  | pileStack c =>
      rw [apply_pileStack_iff] at h
      obtain ⟨-, -, -, -, rfl⟩ := h
      exact hz
  | stackPile c b =>
      rw [apply_stackPile_iff] at h
      obtain ⟨-, -, -, -, rfl⟩ := h
      exact hz
  | pilePile c b =>
      rw [apply_pilePile_iff] at h
      obtain ⟨-, -, -, -, -, -, rfl⟩ := h
      exact hz

theorem State.depthsZero_swapPiles {st : State} (hz : st.depthsZero)
    (i j : Anchor) : (st.swapPiles i j).depthsZero :=
  fun a => by
    show st.depths (Anchor.swap i j a) = 0
    exact hz _

/-- Overwrite the deal (the inert-parameter wash). -/
def State.setDeal (st : State) (d : Deal) : State := { st with deal := d }

theorem State.setDeal_heights (st : State) (d : Deal) :
    (st.setDeal d).heights = st.heights := rfl

theorem State.setDeal_setDeal (st : State) (d₁ d₂ : Deal) :
    (st.setDeal d₁).setDeal d₂ = st.setDeal d₂ := rfl

theorem State.depthsZero_setDeal {st : State} (hz : st.depthsZero) (d : Deal) :
    (st.setDeal d).depthsZero :=
  fun a => by
    show st.depths a = 0
    exact hz a

/-- At an all-hidden-empty state the deal is inert: every move
applies exactly as it did, with the successor washed.  The `reveal`
arm is dead on either side (`depthsZero_topHidden`); for every other
move the two applications share every guard — the stock, board,
depths and heights of a `setDeal` state are definitionally those of
the state — so a shared-scrutinee case analysis closes each arm. -/
theorem State.apply_setDeal_eq_of_depthsZero {st : State} (hz : st.depthsZero)
    (m : Move) (d : Deal) :
    (st.setDeal d).apply m = (st.apply m).map (fun (s : State) => s.setDeal d) := by
  have hzD : (st.setDeal d).depthsZero :=
    fun a => by
      show st.depths a = 0
      exact hz a
  cases m with
  | draw => rfl
  | reveal a =>
      have hnD : (st.setDeal d).topHidden a = none :=
        State.depthsZero_topHidden hzD a
      have hn : st.topHidden a = none := State.depthsZero_topHidden hz a
      show (match (st.setDeal d).topHidden a with
            | none => none
            | some r => _)
        = Option.map (fun (s : State) => { s with deal := d })
            (match st.topHidden a with
            | none => none
            | some r => _)
      rw [hnD, hn]
      rfl
  | deckPile c b =>
      show (match (st.setDeal d).stock.prev with
            | none => none
            | some c' =>
                if c' = c ∧ (st.setDeal d).canPlace c b then
                  match (st.setDeal d).board.attach b c with
                  | none => none
                  | some bdx =>
                      some { st with
                             deal := d,
                             board := bdx,
                             stock := st.stock.removeAt (st.stock.cursor - 1) }
                else none)
        = Option.map (fun (s : State) => { s with deal := d })
            (match st.stock.prev with
             | none => none
             | some c' =>
                 if c' = c ∧ st.canPlace c b then
                   match st.board.attach b c with
                   | none => none
                   | some bdx =>
                       some { st with
                              board := bdx,
                              stock := st.stock.removeAt (st.stock.cursor - 1) }
                 else none)
      rw [show st.stock.prev = (st.setDeal d).stock.prev from rfl,
          show (st.setDeal d).canPlace c b = st.canPlace c b from rfl,
          show (st.setDeal d).board.attach b c = st.board.attach b c from rfl]
      cases hp : (st.setDeal d).stock.prev with
      | none => rfl
      | some c' =>
          show (if c' = c ∧ st.canPlace c b then
                match st.board.attach b c with
                | none => none
                | some bdx =>
                    some { st with
                           deal := d,
                           board := bdx,
                           stock := st.stock.removeAt (st.stock.cursor - 1) }
                else none)
            = Option.map (fun (s : State) => { s with deal := d })
                (if c' = c ∧ st.canPlace c b then
                 match st.board.attach b c with
                 | none => none
                 | some bdx =>
                     some { st with
                            board := bdx,
                            stock := st.stock.removeAt (st.stock.cursor - 1) }
                 else none)
          by_cases hcond : c' = c ∧ st.canPlace c b
          · rw [ite_eq_left hcond, ite_eq_left hcond]
            cases hat : st.board.attach b c with
            | none => rfl
            | some bdx => rfl
          · rw [ite_eq_right hcond, ite_eq_right hcond]; rfl
  | deckStack c =>
      show (match (st.setDeal d).stock.prev with
            | none => none
            | some c' =>
                if c' = c ∧ c.rank.toIdx = (st.setDeal d).heights c.suit then
                  some { st with
                         deal := d,
                         stock := st.stock.removeAt (st.stock.cursor - 1),
                         heights := fun s => if s = c.suit
                           then st.heights s + 1 else st.heights s }
                else none)
        = Option.map (fun (s : State) => { s with deal := d })
            (match st.stock.prev with
             | none => none
             | some c' =>
                 if c' = c ∧ c.rank.toIdx = st.heights c.suit then
                   some { st with
                          stock := st.stock.removeAt (st.stock.cursor - 1),
                          heights := fun s => if s = c.suit
                            then st.heights s + 1 else st.heights s }
                 else none)
      rw [show st.stock.prev = (st.setDeal d).stock.prev from rfl,
          show (st.setDeal d).heights = st.heights from rfl]
      cases hp : (st.setDeal d).stock.prev with
      | none => rfl
      | some c' =>
          show (if c' = c ∧ c.rank.toIdx = st.heights c.suit then
                some { st with
                       deal := d,
                       stock := st.stock.removeAt (st.stock.cursor - 1),
                       heights := fun s => if s = c.suit
                         then st.heights s + 1 else st.heights s }
                else none)
            = Option.map (fun (s : State) => { s with deal := d })
                (if c' = c ∧ c.rank.toIdx = st.heights c.suit then
                 some { st with
                        stock := st.stock.removeAt (st.stock.cursor - 1),
                        heights := fun s => if s = c.suit
                          then st.heights s + 1 else st.heights s }
                 else none)
          by_cases hcond : c' = c ∧ c.rank.toIdx = st.heights c.suit
          · rw [ite_eq_left hcond, ite_eq_left hcond]; rfl
          · rw [ite_eq_right hcond, ite_eq_right hcond]; rfl
  | pileStack c =>
      show (match (st.setDeal d).board.topOf (Sum.inr c),
              (st.setDeal d).board.bottomOf c with
            | none, some b' =>
                if c.rank.toIdx = (st.setDeal d).heights c.suit then
                  some { st with
                         deal := d,
                         board := (st.setDeal d).board.detach b',
                         heights := fun s => if s = c.suit
                           then st.heights s + 1 else st.heights s }
                else none
            | _, _ => none)
        = Option.map (fun (s : State) => { s with deal := d })
            (match st.board.topOf (Sum.inr c), st.board.bottomOf c with
             | none, some b' =>
                 if c.rank.toIdx = st.heights c.suit then
                   some { st with
                          board := st.board.detach b',
                          heights := fun s => if s = c.suit
                            then st.heights s + 1 else st.heights s }
                 else none
             | _, _ => none)
      rw [show st.board.topOf (Sum.inr c)
            = (st.setDeal d).board.topOf (Sum.inr c) from rfl,
          show st.board.bottomOf c = (st.setDeal d).board.bottomOf c from rfl,
          show (st.setDeal d).board.detach = st.board.detach from rfl,
          show (st.setDeal d).heights = st.heights from rfl]
      cases htop : (st.setDeal d).board.topOf (Sum.inr c) with
      | some x => rfl
      | none =>
          cases hb : (st.setDeal d).board.bottomOf c with
          | none => rfl
          | some b' =>
              show (if c.rank.toIdx = st.heights c.suit then
                    some { st with
                           deal := d,
                           board := st.board.detach b',
                           heights := fun s => if s = c.suit
                             then st.heights s + 1 else st.heights s }
                    else none)
                = Option.map (fun (s : State) => { s with deal := d })
                    (if c.rank.toIdx = st.heights c.suit then
                     some { st with
                            board := st.board.detach b',
                            heights := fun s => if s = c.suit
                              then st.heights s + 1 else st.heights s }
                     else none)
              by_cases hcond : c.rank.toIdx = st.heights c.suit
              · rw [ite_eq_left hcond, ite_eq_left hcond]; rfl
              · rw [ite_eq_right hcond, ite_eq_right hcond]; rfl
  | stackPile c b =>
      show (if c.rank.toIdx + 1 = (st.setDeal d).heights c.suit
              ∧ (st.setDeal d).canPlace c b then
              match (st.setDeal d).board.attach b c with
              | none => none
              | some bdx =>
                  some { st with
                         deal := d,
                         board := bdx,
                         heights := fun s => if s = c.suit
                           then st.heights s - 1 else st.heights s }
              else none)
        = Option.map (fun (s : State) => { s with deal := d })
            (if c.rank.toIdx + 1 = st.heights c.suit ∧ st.canPlace c b then
              match st.board.attach b c with
              | none => none
              | some bdx =>
                  some { st with
                         board := bdx,
                         heights := fun s => if s = c.suit
                           then st.heights s - 1 else st.heights s }
              else none)
      rw [show (st.setDeal d).heights = st.heights from rfl,
          show (st.setDeal d).canPlace c b = st.canPlace c b from rfl,
          show (st.setDeal d).board.attach b c = st.board.attach b c from rfl]
      by_cases hcond : c.rank.toIdx + 1 = st.heights c.suit ∧ st.canPlace c b
      · rw [ite_eq_left hcond, ite_eq_left hcond]
        show (match st.board.attach b c with
              | none => none
              | some bdx =>
                  some { st with
                         deal := d,
                         board := bdx,
                         heights := fun s => if s = c.suit
                           then st.heights s - 1 else st.heights s })
          = Option.map (fun (s : State) => { s with deal := d })
              (match st.board.attach b c with
               | none => none
               | some bdx =>
                   some { st with
                          board := bdx,
                          heights := fun s => if s = c.suit
                            then st.heights s - 1 else st.heights s })
        cases hat : st.board.attach b c with
        | none => rfl
        | some bdx => rfl
      · rw [ite_eq_right hcond, ite_eq_right hcond]; rfl
  | pilePile c b =>
      show (match (st.setDeal d).board.bottomOf c with
            | none => none
            | some b' =>
                if b' ≠ b ∧ (st.setDeal d).canMoveRun c b then
                  match ((st.setDeal d).board.detach b').attach b c with
                  | some bdx =>
                      some { st with
                              deal := d,
                              board := bdx }
                  | none => none
                else none)
        = Option.map (fun (s : State) => { s with deal := d })
            (match st.board.bottomOf c with
             | none => none
             | some b' =>
                 if b' ≠ b ∧ st.canMoveRun c b then
                   match (st.board.detach b').attach b c with
                   | some bdx =>
                       some { st with
                              board := bdx }
                   | none => none
                 else none)
      rw [show st.board.bottomOf c = (st.setDeal d).board.bottomOf c from rfl,
          show (st.setDeal d).canMoveRun c b = st.canMoveRun c b from rfl]
      cases hb : (st.setDeal d).board.bottomOf c with
      | none => rfl
      | some b' =>
          show (if b' ≠ b ∧ st.canMoveRun c b then
                match (st.board.detach b').attach b c with
                | some bdx =>
                    some { st with
                            deal := d,
                            board := bdx }
                | none => none
                else none)
            = Option.map (fun (s : State) => { s with deal := d })
                (if b' ≠ b ∧ st.canMoveRun c b then
                 match (st.board.detach b').attach b c with
                 | some bdx =>
                     some { st with
                            board := bdx }
                 | none => none
                 else none)
          by_cases hcond : b' ≠ b ∧ st.canMoveRun c b
          · rw [ite_eq_left hcond, ite_eq_left hcond]
            cases hat : (st.board.detach b').attach b c with
            | none => rfl
            | some bdx => rfl
          · rw [ite_eq_right hcond, ite_eq_right hcond]; rfl

theorem State.run_setDeal_eq_of_depthsZero : ∀ (st : State) (play : List Move)
    (d : Deal), st.depthsZero →
    (st.setDeal d).run play = (st.run play).map (fun s => s.setDeal d) := by
  intro st play
  revert st
  induction play with
  | nil => intro st d hz; rfl
  | cons m ms ih =>
      intro st d hz
      show (match (st.setDeal d).apply m with
            | some s' => s'.run ms
            | none => none)
        = (match st.apply m with
            | some s' => s'.run ms
            | none => none).map (fun (s : State) => s.setDeal d)
      rw [State.apply_setDeal_eq_of_depthsZero hz m d]
      cases hst : st.apply m with
      | none => rfl
      | some st' => exact ih st' d (State.depthsZero_apply hst hz)

theorem State.solvableFrom_setDeal_of_depthsZero {st : State} (hz : st.depthsZero)
    (d : Deal) (h : st.solvableFrom) : (st.setDeal d).solvableFrom := by
  obtain ⟨play, w, hrun, hwin⟩ := h
  refine ⟨play, w.setDeal d, ?_, ?_⟩
  · rw [State.run_setDeal_eq_of_depthsZero st play d hz, hrun]
    rfl
  · show (w.setDeal d).isWin = true
    show w.isWin = true
    exact hwin

/-- At an all-hidden-empty state the deal's content is
solvability-inert: replacing the deal never changes the solvability
verdict.  The pristine board's piles are all fully empty — this is
the content-blindness that makes its seven king landings ONE
future. -/
theorem State.solvableFrom_setDeal_iff_of_depthsZero {st : State} (hz : st.depthsZero)
    (d : Deal) : st.solvableFrom ↔ (st.setDeal d).solvableFrom := by
  constructor
  · exact State.solvableFrom_setDeal_of_depthsZero hz d
  · intro h
    have h2 := State.solvableFrom_setDeal_of_depthsZero
      (st := st.setDeal d) (d := st.deal) hz h
    have heq : (st.setDeal d).setDeal st.deal = st := by
      show ({ st with deal := d } : State).setDeal st.deal = st
      rfl
    rw [heq] at h2
    exact h2

/-! ## §7. The same-deal obstruction and the WF finding -/

/-- A swap-relation between two states moves the deal slices with the
transposition — so two states that share their deal satisfy
`s₁.deal.piles i = s₁.deal.piles j` at the swap's indices. -/
theorem swapPiles_eq_sameDeal_piles (i j : Anchor) {s₁ s₂ : State}
    (hsw : s₁.swapPiles i j = s₂) (hdeal : s₂.deal = s₁.deal) :
    s₁.deal.piles i = s₁.deal.piles j := by
  have h1 : (s₁.swapPiles i j).deal.piles i = s₂.deal.piles i := by rw [hsw]
  rw [State.swapPiles_deal_piles, Anchor.swap_self_left, hdeal] at h1
  exact h1.symm

/-- **The same-deal obstruction**: two states sharing their deal can
be swap-related only by the trivial transposition — a WF deal's
pile slices have pairwise distinct lengths (`a.toIdx + 1`), so `i`
must equal `j`. -/
theorem swapPiles_eq_sameDeal_forced_eq {i j : Anchor} {s₁ s₂ : State}
    (hd : s₁.deal.WF) (hsw : s₁.swapPiles i j = s₂)
    (hdeal : s₂.deal = s₁.deal) : i = j := by
  have hp := swapPiles_eq_sameDeal_piles i j hsw hdeal
  have h1 := hd.1 i
  have h2 := hd.1 j
  rw [← hp] at h2
  rw [h1] at h2
  exact Anchor.toIdx_inj (by omega)

/-- **THE WF FINDING**: a nontrivial pile transposition never lands
in the standard-deal invariant.  `Deal.WF`'s shape clause is pinned
to the seven slots, which have distinct sizes — the swapped slice
at slot `i` is the old slice at `j`, lengths disagree.  The swapped
state remains a coherent game position (§4/§5); it is not a
standard-deal shape. -/
theorem swapPiles_dealWF_blocked {st : State} {i j : Anchor} (hne : i ≠ j)
    (hwf : st.deal.WF) : ¬ (st.swapPiles i j).deal.WF := by
  intro hbad
  have h1 := hbad.1 i
  have h2 := hwf.1 j
  rw [State.swapPiles_deal_piles, Anchor.swap_self_left] at h1
  rw [h2] at h1
  exact hne (Anchor.toIdx_inj (by omega))

/-- The shape clause survives in conjugated form: the swapped deal
satisfies the shape condition read at the transposed indices (the
two readings are definitionally the same condition). -/
theorem swapPiles_deal_shape_conj (st : State) (i j : Anchor) :
    (∀ a, ((st.swapPiles i j).deal.piles a).length = a.toIdx + 1)
      ↔ (∀ a, (st.deal.piles (Anchor.swap i j a)).length = a.toIdx + 1) :=
  ⟨fun h a => h a, fun h a => h a⟩

/-- The ten non-deal conjuncts of `WF`, as a standalone invariant
(the package that the pile transposition *does* preserve). -/
def State.WFsoft (st : State) : Prop :=
  st.depths_le ∧ st.board_edges ∧ st.vis_off_cycle ∧ st.found_off_cycle ∧
  st.founds_gone ∧ st.vis_not_hidden ∧ st.heights_le ∧ st.cursor_le ∧
  st.step_pos ∧ st.stock_wf

theorem State.wfsoft_of_wf {st : State} (h : st.WF) : st.WFsoft :=
  ⟨h.depths_le, h.board_edges, h.vis_off_cycle, h.found_off_cycle, h.founds_gone,
    h.vis_not_hidden, h.heights_le, h.cursor_le, h.step_pos, h.stock_wf⟩

theorem State.wf_of_wfsoft {st : State} (h : st.WFsoft) (hd : st.deal.WF) : st.WF :=
  State.WF.intro hd h.1 h.2.1 h.2.2.1 h.2.2.2.1 h.2.2.2.2.1 h.2.2.2.2.2.1
    h.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.1 h.2.2.2.2.2.2.2.2.2

theorem State.swapPiles_isSome_bottomOf (st : State) (i j : Anchor) (d : Card) :
    ((st.swapPiles i j).board.bottomOf d).isSome = (st.board.bottomOf d).isSome := by
  rw [State.swapPiles_bottomOf]
  cases st.board.bottomOf d with
  | none => rfl
  | some bx => rfl

theorem State.swapPiles_wfsoft {st : State} (i j : Anchor) (h : st.WFsoft) :
    (st.swapPiles i j).WFsoft := by
  obtain ⟨hdepths, hedges, hvis, hfound, hfgone, hvnh, hheights, hcursor, hstep,
    hstock⟩ := h
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, hheights, hcursor, hstep, hstock⟩
  · -- depths_le
    intro a
    show (st.swapPiles i j).depths a ≤ ((st.swapPiles i j).deal.piles a).length
    show st.depths (Anchor.swap i j a) ≤ (st.deal.piles (Anchor.swap i j a)).length
    exact hdepths _
  · -- board_edges
    intro b c hb
    rw [State.swapPiles_board_topOf] at hb
    obtain ⟨hbot, hleg⟩ := hedges _ _ hb
    refine ⟨?_, ?_⟩
    · show (st.swapPiles i j).board.bottomOf c = some b
      rw [State.swapPiles_bottomOf]
      show (st.board.bottomOf c).map (fun x => x.swapBase i j) = _
      rw [hbot]
      show some ((b.swapBase i j).swapBase i j) = some b
      rw [Base.swapBase_swapBase]
    · cases b with
      | inl a =>
          show c.rank = Rank.king ∨ ((st.swapPiles i j).deal.piles a).head? = some c
          rw [State.swapPiles_deal_piles]
          rw [Base.swapBase_inl] at hleg
          exact hleg
      | inr d =>
          rw [Base.swapBase_inr] at hleg
          cases hleg with
          | inl hex =>
              obtain ⟨a, t, rest, hadj, hbase⟩ := hex
              refine Or.inl ⟨Anchor.swap i j a, t, rest, ?_, ?_⟩
              · show (st.swapPiles i j).deal.piles (Anchor.swap i j a) = _
                rw [State.swapPiles_deal_piles, Anchor.swap_swap]
                exact hadj
              · rcases hbase with ⟨a', hth⟩ | hpl
                · refine Or.inl ⟨Anchor.swap i j a', ?_⟩
                  show (st.swapPiles i j).topHidden (Anchor.swap i j a') = _
                  rw [State.swapPiles_topHidden, Anchor.swap_swap]
                  exact hth
                · refine Or.inr ?_
                  show ((st.swapPiles i j).board.bottomOf d).isSome = true
                  rw [State.swapPiles_isSome_bottomOf]
                  exact hpl
          | inr hpl =>
              refine Or.inr ⟨?_, hpl.2⟩
              show ((st.swapPiles i j).board.bottomOf d).isSome = true
              rw [State.swapPiles_isSome_bottomOf]
              exact hpl.1
  · -- vis_off_cycle
    intro c hc
    rw [show (st.swapPiles i j).stock = st.stock from rfl]
    exact hvis c (by
      rw [show st.isVis c = (st.swapPiles i j).isVis c from (State.swapPiles_isVis
        st i j c).symm]
      exact hc)
  · -- found_off_cycle
    intro c hc
    rw [show (st.swapPiles i j).stock = st.stock from rfl]
    exact hfound c hc
  · -- founds_gone
    intro c hc
    refine ⟨?_, (hfgone c hc).2.1, ?_⟩
    · show (st.swapPiles i j).isVis c = false
      rw [State.swapPiles_isVis]
      exact (hfgone c hc).1
    · intro a
      show c ∉ (st.swapPiles i j).hidden a
      show c ∉ st.hidden (Anchor.swap i j a)
      exact (hfgone c hc).2.2 _
  · -- vis_not_hidden
    intro c hc a
    have hc' : st.isVis c = true := by
      rw [show st.isVis c = (st.swapPiles i j).isVis c from (State.swapPiles_isVis
        st i j c).symm]
      exact hc
    show c ∉ (st.swapPiles i j).hidden a
    show c ∉ st.hidden (Anchor.swap i j a)
    exact hvnh c hc' _

/-- The soft invariant transfers in both directions (involutivity). -/
theorem State.wfsoft_swapPiles_iff {st : State} (i j : Anchor) :
    (st.swapPiles i j).WFsoft ↔ st.WFsoft := by
  constructor
  · intro h
    have h2 := State.swapPiles_wfsoft i j h
    rwa [State.swapPiles_swapPiles] at h2
  · intro h
    exact State.swapPiles_wfsoft i j h
